name = "Testworkflow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f6ae6e820374fff3699c7250ee203f55f7aa5474efcde2ba55f707f678598e0"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
