name = "Testworkflow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04e00813ce388db037e268dde192fe5e863068386e9fb99da6bd8390492c597b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
