name = "Testworkflow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ebd128965253bf149c21f874a22fe7ce332708a55dd34390a4b443f1d07eb9"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
