on:
  push:
    branches:
    - master
  workflow_dispatch:
  
jobs:  
  test_echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: cat latest-changelog.md
        run: |
          CHANGELOG=$(cat CHANGELOG.md  | awk '/^# /{count++; if(count>1) exit;} count==1')
          echo $CHANGELOG 
