on:
  push:
    branches:
    - master
  workflow_dispatch:
  
jobs:

  update_modpack:
    uses: shinysht/testmodpack/.github/workflows/update.yml@main
    with:
      token: ${{ secrets.PAT_TOKEN }}
  
  test_echo:
    runs-on: ubuntu-latest
    needs:
      - update_modpack
    steps:
      - name: echo
        run: echo "test2"
