name: testfield

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Commit files and push it
        run: |
          git --no-pager tag --sort version:refname
          vara=$(git tag --sort version:refname | tail -n 1)
          git --no-pager diff --unified=0 $vara -- mods >> temp
          echo "####################"
          ls temp
          cat temp
