name: update repo2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN_2 }}
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Update mods
        run: go run github.com/packwiz/packwiz@latest update --all -y
      
      - name: Commit files and push it
        run: |
          git config --local user.name ${{ secrets.ACTION_USERNAME }}
          git config --local user.email ${{ secrets.ACTION_EMAIL }}
          if ! git diff --exit-code $(git tag --sort version:refname | tail -n 1) -- mods; then
            git add .
            (git --no-pager diff --unified=0 $(git tag --sort version:refname | tail -n 1) -- mods | grep -w "name") | python updateChangelog.py
            git add .
            git commit -m "update mods"
            git push
          fi
