name: update repo

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Update mods
        run: go run github.com/packwiz/packwiz@latest update --all -y
      
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
            git add .
            git commit -m "update mods"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}