name: update repo

on:
  push:
  workflow_dispatch:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Update mods
        run: go run http://github.com/packwiz/packwiz@latest update
      
      - name: Commit files and push it
        run: |
          git add .
          git commit -m "update mods"
          git push