name: update repo2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Update mods
        run: go run github.com/packwiz/packwiz@latest update --all -y
      
      - name: Commit files and push it
        run: |
          git config --local user.name actions-user
          if ! git diff --exit-code $(git tag --sort version:refname | tail -n 1) -- mods; then
            git add .
            git diff --unified=0 $(git tag --sort version:refname | tail -n 1) -- mods | grep -w "name" | python updateChangelog.py
            git add .
            git commit -m "update mods"
            git push
          fi
